import turtle
import tkinter as TK

wn = turtle.Screen()
wn.bgcolor("#add8db")
wn.title("Lao my beloved")
skk = turtle.Turtle()

skk.width(2.5)
skk.speed(45)
skk.left(90)
for i in range(90):
    skk.forward(1)
    skk.right(2)
for i in range(90):
    skk.forward(1)
    skk.left(2)
for i in range(90):
    skk.forward(1)
    skk.right(2)
for i in range(180):
    skk.forward(1.5)
    skk.right(1)
for i in range(90):
    skk.back(1.5)
    skk.left(1)
skk.pencolor("#add8db")
skk.forward(150)
skk.right(90)
skk.forward(200)
skk.right(90)
skk.pencolor("black")
for i in range(180):
    skk.forward(1)
    skk.right(2)
skk.pencolor("#add8db")
skk.forward(300)
skk.pencolor("black")
for i in range(180):
    skk.forward(1)
    skk.right(2)
skk.pencolor("#add8db")
skk.forward(50)
skk.left(90)
skk.forward(250)
skk.left(90)
skk.forward(750)
skk.left(90)
skk.pencolor("black")
skk.forward(150)
skk.left(90)
skk.forward(100)
skk.left(90)
skk.forward(50)
skk.left(90)
skk.forward(50)
skk.right(90)
skk.forward(100)
skk.left(90)
skk.forward(50)
skk.left(180)
skk.forward(50)
skk.pencolor("#add8db")
skk.forward(75)
skk.right(90)
skk.forward(150)
skk.left(160)
skk.pencolor("black")
skk.forward(160)
skk.right(140)
skk.forward(160)
skk.right(110)
skk.forward(110)
skk.right(180)
skk.forward(110)
skk.pencolor("#add8db")
skk.forward(125)
skk.pencolor("black")
for i in range(360):
    skk.forward(1.5)
    skk.left(1)
skk.pencolor("#add8db")
skk.goto(-300,-300)
skk.pencolor("red")
skk.width(5)
skk.left(67.5)
skk.forward(100)
for i in range(70):
    skk.forward(1)
    skk.left(3)
for i in range(70):
    skk.back(1)
    skk.left(3)
skk.left(180)

skk.forward(80)


TK.mainloop()